import { test,expect,type Page } from '@playwright/test';
async function signedIn(page: Page) {
 await page.addInitScript(()=>{
   const uid='00000000-0000-4000-8000-000000000001';const expires=Math.floor(Date.now()/1000)+3600;
   const jwt=btoa(JSON.stringify({alg:'HS256',typ:'JWT'}))+'.'+btoa(JSON.stringify({sub:uid,exp:expires,iat:expires-3600,aud:'authenticated',role:'authenticated'}))+'.test-signature';
   localStorage.setItem('sb-localhost-auth-token',JSON.stringify({access_token:jwt,refresh_token:'test-only-refresh',expires_at:expires,expires_in:3600,token_type:'bearer',user:{id:uid,aud:'authenticated',role:'authenticated',email:'test@example.invalid',app_metadata:{},user_metadata:{user_name:'Test user'},created_at:new Date().toISOString()}}));
 });
}

async function temporary(page:Page,name='documento.txt'){
 await signedIn(page);await page.goto('/');await page.getByRole('button',{name:'✎ File temporaneo',exact:true}).click();await page.getByLabel('Nome',{exact:true}).fill(name);await page.getByRole('button',{name:'Crea',exact:true}).click();
 await expect(page.getByRole('textbox',{name:`Contenuto ${name}`})).toBeVisible();return page.getByRole('textbox',{name:`Contenuto ${name}`});
}
async function selectAll(page:Page){await page.locator('.ql-editor').click();await page.keyboard.press('ControlOrMeta+A');}
test('v1.2 typography, paragraph styles, portable exports and reload preserve formatting',async({page})=>{
 const content=await temporary(page);await content.fill('Hello world');await selectAll(page);
 for(const name of ['Grassetto','Corsivo','Sottolineato','Barrato'])await page.getByRole('button',{name,exact:true}).click();
 await page.getByLabel('Famiglia font').selectOption('Times New Roman');await page.getByLabel('Dimensione font').fill('24');await page.getByRole('button',{name:'+ Dimensione',exact:true}).click();
 await page.getByLabel('Colore testo',{exact:true}).fill('#123456');await page.getByLabel('Evidenziazione testo').fill('#ffdd66');await page.getByRole('button',{name:'Apice',exact:true}).click();
 await page.getByRole('button',{name:'MAIUSCOLO',exact:true}).click();await expect(content).toContainText('HELLO WORLD');
 await page.getByRole('button',{name:'Paragrafo',exact:true}).click();await page.getByRole('button',{name:'Al centro',exact:true}).click();
 await page.getByLabel('Interlinea',{exact:true}).selectOption('2');await page.getByLabel('Prima (pt)',{exact:true}).selectOption('12pt');await page.getByLabel('Dopo (pt)',{exact:true}).selectOption('18pt');await page.getByLabel('Prima riga (pt)',{exact:true}).selectOption('12pt');
 await page.getByLabel('Sfondo paragrafo').fill('#ddccff');await page.getByLabel('Bordi paragrafo').selectOption('all');
 await page.getByRole('button',{name:'Stili',exact:true}).click();await page.getByLabel('Stile testo').selectOption('1');
 await expect(content.locator('h1')).toHaveCSS('text-align','center');await expect(content.locator('sup')).toBeVisible();await expect(content.locator('strong')).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Scarica documento',exact:true}).click();const file=await download;const stream=await file.createReadStream();let value='';for await(const chunk of stream!)value+=chunk.toString();const native=JSON.parse(value);expect(native.delta.some((op:{attributes?:{size?:string}})=>op.attributes?.size==='25pt')).toBe(true);
 await page.reload();await expect(page.locator('.ql-editor strong')).toBeVisible();await expect(page.locator('.ql-editor h1')).toHaveCSS('text-align','center');
 await page.screenshot({path:'test-results/v12-document.png',fullPage:true});await selectAll(page);await page.getByRole('button',{name:'Cancella formattazione',exact:true}).click();await expect(page.locator('.ql-editor strong')).toHaveCount(0);
});
test('v1.2 actual server rich binding retains styles and text across reload and mode changes',async({page})=>{
 await signedIn(page);const id=crypto.randomUUID();await page.route('**/api/v1/projects/*/files',route=>route.fulfill({json:[{id,project_id:'20000000-0000-4000-8000-000000000001',workspace_id:'10000000-0000-4000-8000-000000000001',name:'server.txt',kind:'text',parent_id:null,generation:1,language:'plaintext',metadata_version:1,status:'ready'}]}));
 await page.goto(`/projects/20000000-0000-4000-8000-000000000001/files/${id}`);const content=page.getByRole('textbox',{name:'Contenuto server.txt'});await expect(content).toBeVisible();await content.fill('Server document');await selectAll(page);await page.getByRole('button',{name:'Grassetto',exact:true}).click();await expect(page.getByRole('status')).toHaveText('salvato sul server');
 await page.reload();await expect(content.locator('strong')).toHaveText('Server document');await page.getByRole('button',{name:'Sorgente testo',exact:true}).click();await expect(page.locator('.view-lines')).toContainText('Server document');await page.getByRole('button',{name:'Documento visuale',exact:true}).click();await expect(content.locator('strong')).toHaveText('Server document');await expect(content).toHaveText('Server document');
});
test('v1.2 workspace rail scopes home and file/topic actions use accessible dialogs',async({page})=>{
 await signedIn(page);let nativeDialogs=0;page.on('dialog',async dialog=>{nativeDialogs++;await dialog.dismiss();});await page.goto('/');await page.getByRole('button',{name:'Test workspace',exact:true}).click();
 await expect(page).toHaveURL(/workspaces\/10000000/);await expect(page.getByRole('heading',{name:'Test workspace',exact:true}).first()).toBeVisible();
 await page.getByRole('button',{name:'Gestisci idee.md',exact:true}).first().click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Sposta',exact:true}).click();await expect(page.getByLabel('Cartella di destinazione')).toBeVisible();await page.getByRole('button',{name:'Annulla',exact:true}).click();
 await page.getByRole('button',{name:'Tema di idee.md',exact:true}).first().click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByLabel('Tema del documento o progetto')).toHaveValue('Ricerca');await page.keyboard.press('Escape');expect(nativeDialogs).toBe(0);
});
test('v1.2 pastel backgrounds persist and motion respects reduced-motion',async({page})=>{
 await signedIn(page);await page.goto('/');await page.getByRole('button',{name:'Aspetto',exact:true}).click();await page.getByLabel('Sfondo',{exact:true}).selectOption('glass');await expect(page.locator('html')).toHaveAttribute('data-background','glass');await page.getByRole('button',{name:'☀ Bianco',exact:true}).click();await page.getByRole('button',{name:'Chiudi',exact:true}).click();await page.screenshot({path:'test-results/v12-glass.png',fullPage:true});
 await page.reload();await expect(page.locator('html')).toHaveAttribute('data-background','glass');await page.emulateMedia({reducedMotion:'reduce'});expect(await page.evaluate(()=>getComputedStyle(document.querySelector('.workspace-shell')!,'::before').animationName)).toBe('none');
 await page.getByRole('button',{name:'Aspetto',exact:true}).click();await page.getByLabel('Sfondo',{exact:true}).selectOption('abstract');await page.getByRole('button',{name:'Chiudi',exact:true}).click();await page.screenshot({path:'test-results/v12-abstract.png',fullPage:true});
});
async function selectWords(page:Page,start:number,length:number){await page.locator('.ql-editor').evaluate((element,{start,length})=>{const walker=document.createTreeWalker(element,NodeFilter.SHOW_TEXT);const nodes:Text[]=[];while(walker.nextNode())nodes.push(walker.currentNode as Text);function pos(offset:number){for(const node of nodes){if(offset<=node.length)return {node,offset};offset-=node.length;}return {node:nodes.at(-1)!,offset:nodes.at(-1)!.length};}const a=pos(start),b=pos(start+length);const range=document.createRange();range.setStart(a.node,a.offset);range.setEnd(b.node,b.offset);element.focus();window.getSelection()!.removeAllRanges();window.getSelection()!.addRange(range);document.dispatchEvent(new Event('selectionchange'));},{start,length});await page.waitForTimeout(50);}
test('v1.2 format painter, nested lists and zero paragraph spacing survive reload',async({page})=>{
 const content=await temporary(page,'pennello.txt');await content.fill('alpha beta');await selectWords(page,0,5);await page.getByRole('button',{name:'Grassetto',exact:true}).click();await page.getByRole('button',{name:'Stili',exact:true}).click();await page.getByRole('button',{name:'Copia formato',exact:true}).click();await selectWords(page,6,4);await expect(content.locator('strong')).toHaveText(['alpha','beta']);
 await page.getByRole('button',{name:'Testo',exact:true}).click();await page.getByRole('button',{name:'Maiuscole Iniziali',exact:true}).click();await expect(content).toContainText('Beta');await page.getByRole('button',{name:'Pedice',exact:true}).click();await expect(content.locator('sub')).toBeVisible();await selectAll(page);
 await page.getByRole('button',{name:'Paragrafo',exact:true}).click();await page.getByLabel('Tipo elenco').selectOption('ordered');await page.getByRole('button',{name:'Aumenta rientro',exact:true}).click();await page.getByLabel('Dopo (pt)',{exact:true}).selectOption('0pt');await expect(content.locator('li')).toHaveClass(/ql-indent-1/);await expect(content.locator('li')).toHaveCSS('margin-bottom','0px');
 await page.reload();await expect(page.locator('.ql-editor li')).toHaveClass(/ql-indent-1/);await expect(page.locator('.ql-editor li')).toHaveCSS('margin-bottom','0px');await selectAll(page);await page.getByRole('button',{name:'Paragrafo',exact:true}).click();await page.getByLabel('Tipo elenco').selectOption('square');await expect(page.locator('.ql-editor li')).toHaveClass(/up-list-marker-square/);await page.getByRole('button',{name:'Riduci rientro',exact:true}).click();await expect(page.locator('.ql-editor li')).not.toHaveClass(/ql-indent-1/);
});
test('v1.2 rich collaboration shares formatting, queues offline changes and disables viewers',async({page,browser})=>{
 const id=crypto.randomUUID(),url=`/projects/20000000-0000-4000-8000-000000000001/files/${id}`;
 const context=await browser.newContext(),other=await context.newPage();const viewerContext=await browser.newContext(),viewer=await viewerContext.newPage();
 try{
  for(const client of [page,other,viewer]){await signedIn(client);await client.route('**/api/v1/projects/*/files',route=>route.fulfill({json:[{id,project_id:'20000000-0000-4000-8000-000000000001',workspace_id:'10000000-0000-4000-8000-000000000001',name:'team.txt',kind:'text',parent_id:null,generation:1,language:'plaintext',metadata_version:1,status:'ready'}]}));}
  await viewer.route('**/api/v1/bootstrap',async route=>{const response=await route.fetch();const data=await response.json();data.projects[0].role='viewer';await route.fulfill({json:data});});await viewer.route('**/api/v1/files/*/collaboration-ticket',async route=>{const response=await viewer.request.post('http://localhost:8788/ticket',{data:{token:'viewer',fileId:id,generation:1,document:true}});await route.fulfill({json:await response.json()});});
  await page.goto(url);await page.getByRole('textbox',{name:'Contenuto team.txt'}).fill('Shared');await selectAll(page);await page.getByRole('button',{name:'Grassetto',exact:true}).click();await expect(page.getByRole('status')).toHaveText('salvato sul server');
  await other.goto(url);await viewer.goto(url);await expect(other.locator('.ql-editor strong')).toHaveText('Shared');await expect(viewer.locator('.ql-editor strong')).toHaveText('Shared');await expect(viewer.getByRole('button',{name:'Grassetto',exact:true})).toBeDisabled();await expect(viewer.locator('.ql-editor')).toHaveAttribute('contenteditable','false');
  await context.setOffline(true);await selectAll(other);await other.getByRole('button',{name:'Corsivo',exact:true}).click();await expect(other.getByRole('status')).toContainText('in attesa');await context.setOffline(false);await expect(other.getByRole('status')).toHaveText('salvato sul server',{timeout:20000});await expect(page.locator('.ql-editor em')).toHaveText('Shared');await page.reload();await expect(page.locator('.ql-editor em')).toHaveText('Shared');
 }finally{await context.close();await viewerContext.close();}
});
test('v1.2 native import and temporary promotion retain styles in the durable document',async({page})=>{
 const id=crypto.randomUUID();let name='promosso.txt';
 await page.route('**/api/v1/mutations',async route=>{const body=route.request().postDataJSON();if(['create_standalone','create_file'].includes(body.op)){name=body.args.name;await route.fulfill({json:{id,project_id:'20000000-0000-4000-8000-000000000001',workspace_id:'10000000-0000-4000-8000-000000000001',name,kind:'text',parent_id:null,generation:1,language:'plaintext',metadata_version:1,status:'ready'}});}else await route.continue();});
 await page.route('**/api/v1/projects/*/files',route=>route.fulfill({json:[{id,project_id:'20000000-0000-4000-8000-000000000001',workspace_id:'10000000-0000-4000-8000-000000000001',name,kind:'text',parent_id:null,generation:1,language:'plaintext',metadata_version:1,status:'ready'}]}));
 const content=await temporary(page,'promosso.txt');await content.fill('Keep styles');await selectAll(page);await page.getByRole('button',{name:'Grassetto',exact:true}).click();await page.getByRole('button',{name:'Salva nel DB',exact:true}).click();await expect(page.locator('.ql-editor strong')).toHaveText('Keep styles');await expect(page.getByRole('status')).toHaveText('salvato sul server');await page.reload();await expect(page.locator('.ql-editor strong')).toHaveText('Keep styles');
 await page.goto('/projects/20000000-0000-4000-8000-000000000001');
 name='importato.txt';const importedId=crypto.randomUUID();await page.unroute('**/api/v1/mutations');await page.route('**/api/v1/mutations',route=>route.fulfill({json:{id:importedId,project_id:'20000000-0000-4000-8000-000000000001',workspace_id:'10000000-0000-4000-8000-000000000001',name,kind:'text',parent_id:null,generation:1,language:'plaintext',metadata_version:1,status:'ready'}}));await page.unroute('**/api/v1/projects/*/files');await page.route('**/api/v1/projects/*/files',route=>route.fulfill({json:[{id:importedId,project_id:'20000000-0000-4000-8000-000000000001',workspace_id:'10000000-0000-4000-8000-000000000001',name,kind:'text',parent_id:null,generation:1,language:'plaintext',metadata_version:1,status:'ready'}]}));
 await page.locator('input[type=file]').setInputFiles({name:'importato.txt.ultrapad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'ultrapad-document',version:1,name,delta:[{insert:'Imported style',attributes:{italic:true,size:'18pt'}},{insert:'\n',attributes:{align:'right'}}]}))});await expect(page.locator('.ql-editor em')).toHaveText('Imported style');await expect(page.getByRole('status')).toHaveText('salvato sul server');await page.reload();await expect(page.locator('.ql-editor em')).toHaveText('Imported style');await expect(page.locator('.ql-editor p')).toHaveCount(1);await expect(page.locator('.ql-editor p')).toHaveCSS('text-align','right');
});
