import {test,expect,type Page} from '@playwright/test';
const uid='00000000-0000-4000-8000-000000000001';
async function guest(page:Page){await page.goto('/');await page.getByRole('button',{name:'Continua senza account',exact:true}).click();await expect(page.getByRole('heading',{name:'Il tuo spazio ospite'})).toBeVisible();}
async function create(page:Page,name:string){await page.getByRole('button',{name:'+ Nuovo file',exact:true}).click();await page.getByLabel('Nome',{exact:true}).fill(name);await page.getByRole('button',{name:'Crea',exact:true}).click();await expect(page.getByRole('textbox',{name:`Contenuto ${name}`})).toBeVisible();}
function session(){const exp=Math.floor(Date.now()/1000)+3600;return {access_token:Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64')+'.'+Buffer.from(JSON.stringify({sub:uid,exp,aud:'authenticated',role:'authenticated'})).toString('base64')+'.test-signature',refresh_token:'test-only-refresh',expires_at:exp,expires_in:3600,token_type:'bearer',user:{id:uid,aud:'authenticated',role:'authenticated',email:'google@example.invalid',app_metadata:{provider:'google'},user_metadata:{full_name:'Google Test'},created_at:new Date().toISOString()}};}
test('Google OAuth uses PKCE and root redirect then exchanges callback code',async({page})=>{
 await page.route('http://localhost:8788/auth/v1/authorize**',route=>route.fulfill({contentType:'text/html',body:'Google OAuth fixture'}));await page.goto('/');const outgoing=page.waitForRequest(r=>r.url().includes('/auth/v1/authorize'));await page.getByRole('button',{name:'Accedi con Google →'}).click();const url=new URL((await outgoing).url());expect(url.searchParams.get('provider')).toBe('google');expect(url.searchParams.get('redirect_to')).toBe('http://localhost:5173/');expect(url.searchParams.get('code_challenge')).toBeTruthy();expect(url.searchParams.get('code_challenge_method')).toBe('s256');let exchange:Record<string,unknown>={};await page.route('**/auth/v1/token?grant_type=pkce',async route=>{exchange=route.request().postDataJSON();await route.fulfill({json:session()});});await expect(page.getByText('Google OAuth fixture',{exact:true})).toBeVisible();await page.goto('/?code=fixture-google-code');await expect(page.getByRole('heading',{name:'I tuoi lavori',exact:true})).toBeVisible();expect(exchange.auth_code).toBe('fixture-google-code');expect(exchange.code_verifier).toBeTruthy();await expect(page.locator('.guest-shell')).toHaveCount(0);
});
test('OAuth errors show provider-neutral retry options including guest access',async({page})=>{await page.goto('/?error=access_denied&error_description=fixture');await expect(page.getByRole('alert')).toContainText('Accesso non completato');await expect(page.getByRole('button',{name:'Accedi con Google →'})).toBeEnabled();await expect(page.getByRole('button',{name:'Accedi con GitHub →'})).toBeEnabled();await page.getByRole('button',{name:'Continua senza account'}).click();await expect(page.locator('.guest-shell')).toBeVisible();});
test('guest starts empty, ignores account drafts and private links, and never calls database or rooms',async({page})=>{
 await page.addInitScript(()=>{sessionStorage.setItem('ultrapad-drafts:00000000-0000-4000-8000-000000000001',JSON.stringify([{id:'private',name:'privato.txt',text:'Privato',updated:Date.now()}]));});const forbidden:string[]=[];page.on('request',r=>{if(/\/api\/v1\/|\/rest\/v1\/|\/storage\/v1\/|signInAnonymously/.test(r.url()))forbidden.push(r.url());});page.on('websocket',s=>{if(s.url().includes('/api/')||s.url().includes(':8788'))forbidden.push(s.url());});await guest(page);await expect(page.getByText('privato.txt',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Salva nel DB'})).toHaveCount(0);await create(page,'appunto.txt');await page.getByRole('textbox',{name:'Contenuto appunto.txt'}).fill('Solo ospite');await page.getByRole('button',{name:'Chiudi appunto.txt'}).click();await page.goto('/projects/20000000-0000-4000-8000-000000000001/files/30000000-0000-4000-8000-000000000001');await expect(page.locator('.guest-shell')).toBeVisible();await expect(page.getByText('Test workspace',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'appunto.txt',exact:true}).click();await expect(page.getByRole('textbox',{name:'Contenuto appunto.txt'})).toHaveText('Solo ospite');expect(forbidden).toEqual([]);
});
test('guest rich text survives reload and downloads without sending work to server',async({page})=>{
 await guest(page);await create(page,'documento.txt');const content=page.getByRole('textbox',{name:'Contenuto documento.txt'});await content.fill('Documento ospite');await content.click();await page.keyboard.press('ControlOrMeta+A');await page.getByRole('button',{name:'Grassetto',exact:true}).click();await expect(content.locator('strong')).toHaveText('Documento ospite');await page.reload();await page.getByRole('button',{name:'documento.txt',exact:true}).click();await expect(content.locator('strong')).toHaveText('Documento ospite');const outgoing=page.waitForEvent('download');await page.getByRole('button',{name:'Esporta…',exact:true}).click();await page.getByRole('button',{name:'Scarica documento',exact:true}).click();const file=await outgoing;const stream=await file.createReadStream();let saved='';for await(const chunk of stream!)saved+=chunk.toString();expect(JSON.parse(saved).delta.some((op:{attributes?:{bold?:boolean}})=>op.attributes?.bold)).toBe(true);await page.getByRole('button',{name:'Torna all’accesso'}).click();await expect(page.getByRole('button',{name:'Accedi con Google →'})).toBeVisible();await page.getByRole('button',{name:'Continua senza account'}).click();await expect(page.getByRole('button',{name:'documento.txt',exact:true})).toBeVisible();await page.screenshot({path:'test-results/v15-guest.png',fullPage:true});
});
test('guest imports text, renders preview, renames and deletes with a dialog',async({page})=>{
 await guest(page);await page.getByLabel('Importa file ospite').setInputFiles({name:'bozza.md',mimeType:'text/plain',buffer:Buffer.from('# Anteprima ospite')});await expect(page.locator('.view-lines')).toContainText('# Anteprima ospite',{timeout:20000});await page.getByRole('button',{name:'Anteprima affiancata'}).click();await expect(page.frameLocator('iframe').getByRole('heading',{name:'Anteprima ospite'})).toBeVisible();await page.getByRole('button',{name:'Nome e formato'}).click();await page.getByLabel('Nome',{exact:true}).fill('rinominato.md');await page.getByRole('button',{name:'Salva',exact:true}).click();await expect(page.locator('.view-lines')).toContainText('# Anteprima ospite',{timeout:20000});await page.getByRole('button',{name:'Elimina file',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Conferma',exact:true}).click();await expect(page.getByText('Nessun documento. Crea il tuo primo file.')).toBeVisible();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('guest storage failure keeps live text downloadable and blocks leaving editor',async({page})=>{
 await guest(page);await create(page,'sicuro.txt');await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='ultrapad-drafts:guest-v1.5')throw new Error('test storage quota');return original.call(this,key,value);};});await page.getByRole('textbox',{name:'Contenuto sicuro.txt'}).fill('Da proteggere');await expect(page.getByRole('button',{name:'Chiudi sicuro.txt'})).toBeDisabled();await expect(page.getByRole('button',{name:'Torna all’accesso'})).toBeDisabled();await expect(page.getByRole('textbox',{name:'Contenuto sicuro.txt'})).toHaveText('Da proteggere');const outgoing=page.waitForEvent('download');await page.getByRole('button',{name:'Esporta…',exact:true}).click();await page.getByRole('button',{name:'Scarica testo',exact:true}).click();const download=await outgoing;const stream=await download.createReadStream();let saved='';for await(const chunk of stream!)saved+=chunk.toString();expect(saved).toContain('Da proteggere');
});
test('authenticated Google account sees its server workspace without guest document promotion',async({page})=>{
 await guest(page);await create(page,'non-promosso.txt');await page.getByRole('textbox',{name:'Contenuto non-promosso.txt'}).fill('Solo locale');await page.getByRole('button',{name:'Torna all’accesso'}).click();const value=session();await page.evaluate(value=>localStorage.setItem('sb-localhost-auth-token',JSON.stringify(value)),value);let mutations=0;page.on('request',r=>{if(r.url().includes('/api/v1/mutations'))mutations++;});await page.reload();await expect(page.getByRole('heading',{name:'I tuoi lavori',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Test workspace',exact:true})).toBeVisible();await expect(page.getByText('non-promosso.txt',{exact:true})).toHaveCount(0);expect(mutations).toBe(0);
});
