import { useState } from 'react';
import type { FileRecord } from '../../../packages/contracts/src/index';
import { canEdit, type Role } from '../../../packages/domain/src/index';
import { topicFor } from '../../../packages/presentation/src/tools';
import type { Draft } from './drafts';
type Project={id:string;name:string;workspace_id:string;theme?:string;is_personal?:boolean;role:Role};
export default function Dashboard({files,projects,userId,recent,drafts,loading,error,retry,open,openDraft,createFile,createDraft,createProject,setTopic,manage,workspaceName}:{workspaceName?:string;manage:(file:FileRecord)=>void;files:FileRecord[];projects:Project[];userId:string;recent:string[];drafts:Draft[];loading:boolean;error?:string;retry:()=>void;open:(file:FileRecord)=>void;openDraft:(id:string)=>void;createFile:()=>void;createDraft:()=>void;createProject:()=>void;setTopic:(file:FileRecord)=>void}) {
 const [search,setSearch]=useState('');const [view,setView]=useState<'all'|'recent'|'team'|'topics'>('all');
 const matching=files.filter(f=>`${f.name} ${projects.find(p=>p.id===f.project_id)?.name??''} ${topicFor(f,projects.find(p=>p.id===f.project_id)?.theme)}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const recentFiles=recent.map(id=>matching.find(f=>f.id===id)).filter((f):f is FileRecord=>Boolean(f));
 const team=matching.filter(f=>f.last_modified_by && f.last_modified_by!==userId);
 const matchingProjects=projects.filter(p=>!p.is_personal && `${p.name} ${p.theme??''}`.toLowerCase().includes(search.toLowerCase()));
 const projectCard=(p:Project)=><a className="project-card" href={`/projects/${p.id}`} key={p.id}><span>◇</span><h3>{p.name}</h3><p>{p.theme||'Progetto di squadra'}</p></a>;
 const card=(file:FileRecord)=>{const project=projects.find(p=>p.id===file.project_id);return <article className="work-card" key={file.id}><button className="card-open" onClick={()=>open(file)}><span className="file-icon">{file.name.split('.').pop()?.slice(0,4).toUpperCase()}</span><h3>{file.name}</h3><p>{project?.is_personal?'File personale':project?.name??'Progetto'}</p><small>{file.updated_at?new Date(file.updated_at).toLocaleString('it-IT'):'Data non disponibile'}{file.last_modified_by && <span> · {file.last_modified_by===userId?'Tu':'Team'}</span>}</small></button><button className="topic-pill" disabled={!project || !canEdit(project.role)} aria-label={`Tema di ${file.name}`} onClick={()=>setTopic(file)}>{topicFor(file,project?.theme)} ↗</button>{project&&canEdit(project.role)&&<button className="card-manage" aria-label={`Gestisci ${file.name}`} onClick={()=>manage(file)}>⋯</button>}</article>;};
 const section=(title:string,rows:FileRecord[],empty:string)=><section className="dashboard-section"><div className="section-title"><h2>{title}</h2><span>{rows.length}</span></div>{rows.length?<div className="work-grid">{rows.map(card)}</div>:<p className="empty-note">{empty}</p>}</section>;
 return <div className="dashboard"><div className="dashboard-hero"><div><span className="eyebrow">IL TUO PUNTO DI PARTENZA</span><h2>{workspaceName??<>Riprendi un’idea.<br/>Falla crescere insieme.</>}</h2><p>{workspaceName?'Progetti e documenti di questo workspace.':'Progetti, file personali e appunti temporanei in un unico spazio.'}</p></div><div className="quick-actions"><button className="primary" onClick={createFile}>+ File singolo</button><button onClick={createDraft}>✎ File temporaneo</button><button onClick={createProject}>◇ Nuovo progetto</button></div></div>
 <div className="dashboard-controls"><input type="search" aria-label="Cerca lavori" placeholder="Cerca file, progetto o tema…" value={search} onChange={e=>setSearch(e.target.value)}/><nav aria-label="Raggruppa lavori" className="segmented">{([['all','Panoramica'],['recent','Aperti di recente'],['team','Attività del team'],['topics','Per tema']] as const).map(([value,label])=><button key={value} aria-pressed={view===value} onClick={()=>setView(value)}>{label}</button>)}</nav></div>
 {loading && <p>Caricamento lavori…</p>}{error && <div className="notice" role="alert">{error}<button onClick={retry}>Ricarica lavori</button></div>}
 {!error && (view==='all'||view==='recent') && section('Aperti di recente',recentFiles,'Apri un file: lo ritroverai qui. La cronologia è personale a questo browser.')}
 {!error && view==='all' && section('Ultimi lavori modificati',matching.slice(0,12),'Crea un file singolo oppure un progetto per iniziare.')}
 {!error && (view==='all'||view==='team') && section('Ultime modifiche del team',team.slice(0,12),'Nessuna modifica di altri collaboratori nei lavori caricati.')}
 {view==='topics' && [...new Set([...matching.map(f=>topicFor(f,projects.find(p=>p.id===f.project_id)?.theme)),...matchingProjects.map(p=>p.theme||'Progetti')])].sort().map(topic=>{const topicFiles=matching.filter(f=>topicFor(f,projects.find(p=>p.id===f.project_id)?.theme)===topic);const topicProjects=matchingProjects.filter(p=>(p.theme||'Progetti')===topic);return <section className="dashboard-section" key={topic}><div className="section-title"><h2>{topic}</h2><span>{topicFiles.length+topicProjects.length}</span></div><div className="work-grid">{topicFiles.map(card)}{topicProjects.map(projectCard)}</div></section>;})}
 {view==='all' && <section className="dashboard-section"><div className="section-title"><h2>Progetti</h2><span>{projects.filter(p=>!p.is_personal).length}</span></div><div className="work-grid">{matchingProjects.map(projectCard)}</div></section>}
 {(view==='all'||view==='recent') && <section className="dashboard-section"><div className="section-title"><h2>Temporanei di questa scheda</h2><span>{drafts.length}</span></div><p className="muted">Restano dopo un ricaricamento, fino alla chiusura della scheda. Scaricali o salvali nel DB per conservarli.</p><div className="work-grid">{drafts.filter(d=>d.name.toLowerCase().includes(search.toLowerCase())).map(d=><button className="draft-card" key={d.id} onClick={()=>openDraft(d.id)}><span>✎</span><h3>{d.name}</h3><small>{new Date(d.updated).toLocaleString('it-IT')} · Temporaneo</small></button>)}</div></section>}
 <p className="muted">Fino a 100 file accessibili, ordinati per ultima modifica. I temi assegnati prevalgono sul raggruppamento per formato. L’attività del server può aggiornarsi con un breve ritardo.</p>
 </div>;
}
