import {useEffect,useRef,useState} from 'react';
import {auth,request} from './api';
import {useQuery} from '@tanstack/react-query';
import {profileFor,type Profile} from '../../../packages/profile/src/index';
import type {User} from '@supabase/supabase-js';
export function Avatars({profiles,active=true}:{profiles:Profile[];active?:boolean}){return <span className="avatars" aria-label={active?'Persone con il file aperto':'Profilo personale'}>{profiles.map(p=><span className="avatar" key={p.id} title={`${p.firstName} ${p.lastName}${active?' · file aperto':''}`} aria-label={`${p.firstName} ${p.lastName}${active?' · file aperto':''}`}>{`${p.firstName[0]??''}${p.lastName[0]??''}`}{p.avatar&&<img src={p.avatar} alt="" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.style.display='none';}}/>}</span>)}</span>;}
export function FilePresence({id}:{id:string}){const ref=useRef<HTMLSpanElement>(null);const [visible,setVisible]=useState(false);useEffect(()=>{const observer=new IntersectionObserver(entries=>setVisible(entries.some(e=>e.isIntersecting)));if(ref.current)observer.observe(ref.current);return()=>observer.disconnect();},[]);const query=useQuery({queryKey:['presence',id],enabled:visible,queryFn:()=>request<Profile[]>(`/files/${id}/presence`),refetchInterval:10000});return <span ref={ref} className="file-presence"><Avatars profiles={query.error?[]:query.data??[]}/>{query.error&&<small className="muted">Presenza non disponibile</small>}</span>;}
export function AccountProfile({user}:{user:User}){
 const initial=profileFor(user.id,user.email,user.user_metadata);const [profile,setProfile]=useState(initial);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function upload(file:File){setBusy(true);setMessage('');try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Scegli PNG, JPEG o WebP fino a 5 MiB.');const bitmap=await createImageBitmap(file);try{const canvas=document.createElement('canvas');const size=Math.min(bitmap.width,bitmap.height);let avatar='';for(const pixels of [64,48,32]){canvas.width=pixels;canvas.height=pixels;const context=canvas.getContext('2d')!;context.drawImage(bitmap,(bitmap.width-size)/2,(bitmap.height-size)/2,size,size,0,0,pixels,pixels);for(const quality of [0.65,0.4,0.25]){avatar=canvas.toDataURL('image/jpeg',quality);if(avatar.length<=1800)break;}if(avatar.length<=1800)break;}if(avatar.length>1800)throw new Error('Immagine troppo complessa, scegli una foto più semplice.');setProfile(p=>({...p,avatar}));}finally{bitmap.close();}}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const {error}=await auth!.auth.updateUser({data:{first_name:profile.firstName.trim(),last_name:profile.lastName.trim(),profile_avatar:profile.avatar}});if(error)throw error;setMessage('Profilo salvato.');}catch{setMessage('Profilo non salvato. Verifica la connessione e riprova.');}finally{setBusy(false);}}}><Avatars active={false} profiles={[profile]}/><label>Nome<input required maxLength={80} value={profile.firstName} onChange={e=>setProfile(p=>({...p,firstName:e.target.value}))}/></label><label>Cognome<input maxLength={80} value={profile.lastName} onChange={e=>setProfile(p=>({...p,lastName:e.target.value}))}/></label><label>Immagine di profilo<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void upload(f);}}/></label><button type="button" onClick={()=>setProfile(p=>({...p,avatar:''}))}>Rimuovi immagine</button><button className="primary" disabled={busy}>Salva profilo</button>{message&&<p role="status">{message}</p>}</form>;
}
