export type TextTool={label:string;before:string;after?:string;placeholder?:string};
const tool=(label:string,before:string,after='',placeholder='')=>({label,before,after,placeholder});
export function toolsFor(name:string):{label:string;tools:TextTool[];format:boolean;validate?:'json'|'xml'} {
 const ext=name.split('.').pop()?.toLowerCase()??'';
 switch(ext){
 case 'md':return {label:'Markdown',format:false,tools:[tool('Titolo','# ','','Titolo'),tool('Grassetto','**','**','testo'),tool('Corsivo','*','*','testo'),tool('Link','[','](https://example.com)','testo'),tool('Checklist','- [ ] ','','Attività'),tool('Blocco codice','\n```\n','\n```\n','codice'),tool('Tabella','\n| Colonna | Colonna |\n| --- | --- |\n| Valore | Valore |\n')]};
 case 'json':return {label:'JSON',format:true,validate:'json',tools:[tool('Oggetto','{\n  "chiave": "valore"\n}'),tool('Array','[\n  \n]'),tool('Proprietà','"chiave": "valore"')]};
 case 'xml':return {label:'XML',format:false,validate:'xml',tools:[tool('Elemento','<elemento>','</elemento>','valore'),tool('Attributo',' nome="valore"'),tool('Commento','<!-- ',' -->','commento'),tool('CDATA','<![CDATA[',']]>','testo')]};
 case 'html':return {label:'HTML',format:true,tools:[tool('Pagina','<!doctype html>\n<html lang="it">\n<head><meta charset="utf-8"><title>Pagina</title></head>\n<body>\n</body>\n</html>'),tool('Titolo','<h1>','</h1>','Titolo'),tool('Link','<a href="https://example.com">','</a>','Link'),tool('Immagine','<img src="immagine.png" alt="Descrizione">'),tool('Sezione','<section>\n','\n</section>','contenuto')]};
 case 'css':return {label:'CSS',format:true,tools:[tool('Regola','.classe {\n  \n}'),tool('Flexbox','display: flex;\ngap: 1rem;\nalign-items: center;'),tool('Grid','display: grid;\ngrid-template-columns: repeat(2, 1fr);\ngap: 1rem;'),tool('Media query','@media (max-width: 768px) {\n  \n}')]};
 case 'js':return {label:'JavaScript',format:true,tools:[tool('Funzione','function nome(parametro) {\n  return parametro;\n}'),tool('Async','async function carica() {\n  const response = await fetch("/api");\n  return response.json();\n}'),tool('Commento','/* ',' */','commento')]};
 case 'ts':return {label:'TypeScript',format:true,tools:[tool('Interfaccia','interface Modello {\n  id: string;\n}'),tool('Tipo','type Identificativo = string;'),tool('Funzione','function nome(parametro: string): string {\n  return parametro;\n}')]};
 case 'java':return {label:'Java',format:false,tools:[tool('Classe','public class Nome {\n\n}'),tool('Main','public static void main(String[] args) {\n\n}'),tool('Metodo','public void nome() {\n\n}'),tool('Javadoc','/**\n * Descrizione\n */\n')]};
 case 'cs':return {label:'C#',format:false,tools:[tool('Classe','public class Nome\n{\n\n}'),tool('Proprietà','public string Nome { get; set; } = string.Empty;'),tool('Metodo','public void Nome()\n{\n\n}'),tool('Namespace','namespace Progetto;\n')]};
 case 'py':return {label:'Python',format:false,tools:[tool('Funzione','def nome(parametro):\n    return parametro\n'),tool('Classe','class Nome:\n    def __init__(self):\n        pass\n'),tool('Main','if __name__ == "__main__":\n    main()\n'),tool('Docstring','"""','"""','Descrizione')]};
 case 'tex':return {label:'LaTeX · sorgente',format:false,tools:[tool('Documento','\\documentclass{article}\n\\usepackage[utf8]{inputenc}\n\\begin{document}\n\n\\end{document}\n'),tool('Sezione','\\section{','}','Titolo'),tool('Grassetto','\\textbf{','}','testo'),tool('Formula','\\[\n','\n\\]','a^2 + b^2 = c^2'),tool('Elenco','\\begin{itemize}\n\\item Voce\n\\end{itemize}\n'),tool('Citazione','\\cite{','}','chiave')]};
 case 'bib':return {label:'BibTeX',format:false,tools:[tool('Articolo','@article{chiave,\n  author = {Autore},\n  title = {Titolo},\n  journal = {Rivista},\n  year = {2026}\n}\n'),tool('Libro','@book{chiave,\n  author = {Autore},\n  title = {Titolo},\n  publisher = {Editore},\n  year = {2026}\n}\n')]};
 default:return {label:'Testo semplice',format:false,tools:[tool('Elenco','• ','','Voce'),tool('Separatore','\n────────────────────\n'),tool('Data',new Date().toLocaleDateString('it-IT'))]};
 }
}
export function insertion(tool:TextTool,selected:string){return tool.before+(selected||tool.placeholder||'')+(tool.after??'');}
export function topicFor(file:{name:string;theme?:string},projectTheme?:string){return file.theme?.trim()||projectTheme?.trim()||({md:'Note',txt:'Note',tex:'Tesi e ricerca',bib:'Tesi e ricerca',json:'Dati',xml:'Dati',html:'Web',css:'Web'} as Record<string,string>)[file.name.split('.').pop()?.toLowerCase()??'']||'Codice e altri file';}
